# Generated by Django 3.1.2 on 2021-08-31 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cichild_database', '0031_auto_20210831_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TankFragmentAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('tank_fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankFragment', to='app_cichild_database.tankfragment')),
            ],
            bases=('app_cichild_database.action',),
        ),
        migrations.CreateModel(
            name='FishActionMove',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('new_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_location', to='app_cichild_database.tankfragment')),
                ('old_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_location', to='app_cichild_database.tankfragment')),
            ],
            bases=('app_cichild_database.action',),
        ),
        migrations.CreateModel(
            name='FishAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.fish')),
            ],
            bases=('app_cichild_database.action',),
        ),
        migrations.CreateModel(
            name='CommentAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.comment')),
            ],
            bases=('app_cichild_database.action',),
        ),
        migrations.CreateModel(
            name='ClutchAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('clutch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.clutch')),
            ],
            bases=('app_cichild_database.action',),
        ),
        migrations.CreateModel(
            name='MergeSplitTankFragment',
            fields=[
                ('tankfragmentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.tankfragmentaction')),
                ('tank_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank1', to='app_cichild_database.tankfragment')),
                ('tank_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank2', to='app_cichild_database.tankfragment')),
            ],
            bases=('app_cichild_database.tankfragmentaction',),
        ),
        migrations.CreateModel(
            name='ChangeTankFragmentSpecie',
            fields=[
                ('tankfragmentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.tankfragmentaction')),
                ('old_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.specie')),
            ],
            bases=('app_cichild_database.tankfragmentaction',),
        ),
    ]
