# Generated by Django 3.1.2 on 2021-08-31 10:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cichild_database', '0033_remove_action_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergeSplitTankFragment',
            new_name='MergeSplitTankFragmentAction',
        ),
    ]
