# Generated by Django 3.1.2 on 2021-08-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0034_auto_20210831_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.actiontype'),
            preserve_default=False,
        ),
    ]
