# Generated by Django 3.1.2 on 2021-08-31 10:20

import app_cichild_database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0036_auto_20210831_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=app_cichild_database.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
