# Generated by Django 3.1.2 on 2021-09-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0037_auto_20210831_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishActionRename',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.action')),
                ('new_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_name', to='app_cichild_database.fishname')),
                ('old_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_name', to='app_cichild_database.fishname')),
            ],
            bases=('app_cichild_database.action',),
        ),
    ]
