# Generated by Django 3.1.2 on 2021-09-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0038_fishactionrename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishactionrename',
            old_name='new_location',
            new_name='new_name',
        ),
    ]
