# Generated by Django 3.1.2 on 2021-09-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0039_auto_20210901_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishactionmove',
            name='action_ptr',
        ),
        migrations.RemoveField(
            model_name='fishactionrename',
            name='action_ptr',
        ),
        migrations.AddField(
            model_name='fishactionmove',
            name='fishaction_ptr',
            field=models.OneToOneField(auto_created=True, default=7, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.fishaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishactionrename',
            name='fishaction_ptr',
            field=models.OneToOneField(auto_created=True, default=7, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.fishaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fish',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='dof',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='transgene',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
