# Generated by Django 3.1.2 on 2021-09-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0040_auto_20210901_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
