# Generated by Django 3.1.2 on 2021-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishname',
            old_name='is_use',
            new_name='in_use',
        ),
    ]
