# Generated by Django 3.1.2 on 2021-06-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0004_auto_20210621_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankfragment',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.specie'),
        ),
    ]
