# Generated by Django 3.1.2 on 2021-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0005_tankfragment_specie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tankfragment',
            name='merged_into',
        ),
        migrations.RemoveField(
            model_name='tankfragment',
            name='name',
        ),
        migrations.AddField(
            model_name='tankfragment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tankfragment',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tankfragment',
            name='merged_of',
            field=models.ManyToManyField(to='app_cichild_database.TankFragment'),
        ),
        migrations.AddField(
            model_name='tankfragment',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
