# Generated by Django 3.1.2 on 2021-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0006_auto_20210623_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='is_missing',
            field=models.BooleanField(default=False),
        ),
    ]
