# Generated by Django 3.1.2 on 2021-06-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0007_auto_20210623_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.tankfragment'),
        ),
    ]
