# Generated by Django 3.1.2 on 2021-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0008_auto_20210623_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankfragment',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
