# Generated by Django 3.1.2 on 2021-06-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0011_auto_20210623_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='location_hsitory',
            new_name='location_history',
        ),
    ]
