# Generated by Django 3.1.2 on 2021-06-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0012_auto_20210623_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='tank',
        ),
    ]
