# Generated by Django 3.1.2 on 2021-06-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0014_specie_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankfragment',
            name='end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tankfragment',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
