# Generated by Django 3.1.2 on 2021-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0016_tank_total_slots_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specie',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='specie',
            name='writing_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tanksystem',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
