# Generated by Django 3.1.2 on 2021-07-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0017_auto_20210624_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutch',
            name='dof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='dof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishlocationhistory',
            name='move_out_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
