# Generated by Django 3.1.2 on 2021-07-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0018_auto_20210701_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
