# Generated by Django 3.1.2 on 2021-07-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0019_tank_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishname',
            name='in_use',
        ),
    ]
