# Generated by Django 3.1.2 on 2021-07-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0020_remove_fishname_in_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clutch',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='clutch',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clutch',
            name='usage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
