# Generated by Django 3.1.2 on 2021-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0021_auto_20210727_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutch',
            name='clutching_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
