# Generated by Django 3.1.2 on 2021-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0023_clutch_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clutch',
            old_name='comments',
            new_name='comment',
        ),
    ]
