# Generated by Django 3.1.2 on 2021-07-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0024_auto_20210728_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishlocationhistory',
            name='move_in_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
