# Generated by Django 3.1.2 on 2021-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0025_fishlocationhistory_move_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishlocationhistory',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
