# Generated by Django 3.1.2 on 2021-07-28 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0026_fishlocationhistory_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='location_history',
        ),
        migrations.AddField(
            model_name='fishlocationhistory',
            name='fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.fish'),
        ),
    ]
