# Generated by Django 3.1.2 on 2021-08-31 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0027_auto_20210728_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishlocationhistory',
            name='fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.fish'),
        ),
    ]
