# Generated by Django 3.1.2 on 2021-08-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0028_auto_20210831_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='writing_color',
        ),
        migrations.AddField(
            model_name='tanksystem',
            name='landmark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
