# Generated by Django 3.1.2 on 2021-08-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0030_auto_20210831_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clutch',
            name='babies_age',
        ),
        migrations.RemoveField(
            model_name='clutch',
            name='clutching_count',
        ),
    ]
