# Generated by Django 3.1.2 on 2021-09-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0031_auto_20210831_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='dof',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='transgene',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
