# Generated by Django 3.1.2 on 2021-09-01 11:52

import app_cichild_database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cichild_database', '0032_auto_20210901_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FishAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', app_cichild_database.models.CustomDateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.fish')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.actiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TankFragmentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', app_cichild_database.models.CustomDateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tank_fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TankFragment', to='app_cichild_database.tankfragment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.actiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', app_cichild_database.models.CustomDateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.comment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.actiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClutchAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', app_cichild_database.models.CustomDateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('clutch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.clutch')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_cichild_database.actiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MergeSplitTankFragmentAction',
            fields=[
                ('tankfragmentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.tankfragmentaction')),
                ('tank_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank1', to='app_cichild_database.tankfragment')),
                ('tank_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tank2', to='app_cichild_database.tankfragment')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_cichild_database.tankfragmentaction',),
        ),
        migrations.CreateModel(
            name='FishActionRename',
            fields=[
                ('fishaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.fishaction')),
                ('new_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_name', to='app_cichild_database.fishname')),
                ('old_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_name', to='app_cichild_database.fishname')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_cichild_database.fishaction',),
        ),
        migrations.CreateModel(
            name='FishActionMove',
            fields=[
                ('fishaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.fishaction')),
                ('new_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_location', to='app_cichild_database.tankfragment')),
                ('old_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_location', to='app_cichild_database.tankfragment')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_cichild_database.fishaction',),
        ),
        migrations.CreateModel(
            name='ChangeTankFragmentSpecie',
            fields=[
                ('tankfragmentaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_cichild_database.tankfragmentaction')),
                ('old_specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cichild_database.specie')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_cichild_database.tankfragmentaction',),
        ),
    ]
