# Generated by Django 3.1.2 on 2021-09-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0033_actiontype_changetankfragmentspecie_clutchaction_commentaction_fishaction_fishactionmove_fishactionr'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetankfragmentspecie',
            name='new_specie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='new_specie', to='app_cichild_database.specie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changetankfragmentspecie',
            name='old_specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_specie', to='app_cichild_database.specie'),
        ),
    ]
