# Generated by Django 3.1.2 on 2021-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0034_auto_20210901_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutch',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
