# Generated by Django 3.1.2 on 2021-09-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0035_auto_20210901_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutchaction',
            name='txt_date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='commentaction',
            name='txt_date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='fishaction',
            name='txt_date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tankfragmentaction',
            name='txt_date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
