# Generated by Django 3.1.2 on 2021-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0036_auto_20210901_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clutchaction',
            name='txt_date',
        ),
        migrations.RemoveField(
            model_name='commentaction',
            name='txt_date',
        ),
        migrations.RemoveField(
            model_name='fishaction',
            name='txt_date',
        ),
        migrations.RemoveField(
            model_name='tankfragmentaction',
            name='txt_date',
        ),
        migrations.AlterField(
            model_name='clutchaction',
            name='date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='commentaction',
            name='date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fishaction',
            name='date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tankfragmentaction',
            name='date',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
