# Generated by Django 3.1.2 on 2021-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0038_backupmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='usage',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
