# Generated by Django 3.1.2 on 2022-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0039_fish_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutch',
            name='death_data',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clutch',
            name='include_in_csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clutch',
            name='switch_to_father_data',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clutch',
            name='switch_to_father_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
