# Generated by Django 3.1.2 on 2022-02-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0040_auto_20220228_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clutch',
            old_name='death_data',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='clutch',
            old_name='switch_to_father_data',
            new_name='switch_to_father_date',
        ),
    ]
