# Generated by Django 3.1.2 on 2022-02-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0041_auto_20220228_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishNameCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1)),
            ],
        ),
    ]
