# Generated by Django 3.1.2 on 2022-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0042_fishnamecharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutch',
            name='include_in_csv',
            field=models.BooleanField(default=True),
        ),
    ]
