# Generated by Django 3.2.16 on 2024-03-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cichild_database', '0043_auto_20220302_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutch',
            name='female',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clutch_female', to='app_cichild_database.fish'),
        ),
        migrations.AlterField(
            model_name='clutch',
            name='male',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clutch_male', to='app_cichild_database.fish'),
        ),
    ]
